"""Download data from an nginx HTTP server to a Crusoe shared disk
using parallel aria2c worker pods on Kubernetes.

The source file list is a pre-generated aria2c input file (downloads.txt)
where each entry has mirror URLs and per-file options (dir=, out=).

Pipeline:
  1. Parse downloads.txt into individual download entries.
  2. Split entries round-robin into per-worker shard files.
  3. Spin up a master pod that mounts the shared disk and copies shards onto it.
  4. Launch NUM_PODS aria2c worker pods; each downloads its shard.
  5. Wait for all workers to finish, then clean up.

Prerequisites:
  Run `ansible-playbook` first to provision the PV/PVC and generate downloads.txt.

Usage:
  python3 aria2c-download.py
"""

import subprocess
import os
import json
import time
import logging

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

## CONFIGURATION ##
# Update these values based on your terraform.tfvars and Terraform outputs.
#
# NUM_PODS: run `terraform output aria2c_num_pods` for the recommended value
#           (= nodepool_vm_count × 8).  Example: 4 VMs → NUM_PODS = 32.
#           8 pods per VM spreads NIC receive processing across more vCPUs.
NUM_PODS = 48

# PVC_NAME: name of the PersistentVolumeClaim provisioned by Ansible.
PVC_NAME = "aria2c-vast-csi-import"

DOWNLOADS_FILE = "downloads.txt"       # aria2c input file generated by Ansible
MASTER_POD_NAME = "aria2c-master"      # Staging pod used to copy shards onto the PVC

# The PVC is mounted at this path in every pod.
# This must match the `dir=` values in downloads.txt so aria2c writes to the PVC.
DATA_MOUNT = "/vast"

# Shards are written into a subdirectory on the PVC so they don't pollute the
# dataset root.  Workers read from here; the path is inside DATA_MOUNT so the
# same PVC mount covers both.
SHARD_SUBDIR = ".aria2-shards"          # relative to DATA_MOUNT

# aria2c credentials — must match http_user and http_password in terraform.tfvars.
HTTP_USER = "transfer-user"
HTTP_PASSWD = "CHANGE_ME"

# aria2c concurrency settings.
# Connections per pod  = MAX_CONCURRENT_DOWNLOADS × MAX_CONNECTION_PER_SERVER = 64 × 16 = 1024
# Connections per node = pods_per_node × 1024 = 8 × 1024 = 8192
# Per source server    = (NUM_PODS × 1024) / source_server_vm_count
# nginx with sendfile() has ~97% CPU headroom at these levels.
MAX_CONCURRENT_DOWNLOADS = 64
MAX_CONNECTION_PER_SERVER = 16

# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------

def parse_aria2c_entries(filepath: str) -> list[str]:
    """Parse an aria2c input file into a list of individual download entries.

    Each entry is a URL line (possibly tab-separated mirrors) followed by
    indented option lines (dir=, out=, ...).  Blank lines between entries
    are treated as separators but are not required.

    Returns a list of strings, each being one complete aria2c entry block.
    """
    entries: list[str] = []
    current: list[str] = []

    with open(filepath) as fh:
        for raw in fh:
            line = raw.rstrip('\n')
            if not line.strip():
                # Blank line — flush current entry
                if current:
                    entries.append('\n'.join(current))
                    current = []
            elif line[0] != ' ' and line[0] != '\t':
                # Non-indented, non-blank line → URL line → new entry
                if current:
                    entries.append('\n'.join(current))
                current = [line]
            else:
                # Indented option line — belongs to current entry
                current.append(line)

    if current:
        entries.append('\n'.join(current))

    logging.info(f"Parsed {len(entries)} download entries from '{filepath}'.")
    return entries


# ---------------------------------------------------------------------------
# Sharding
# ---------------------------------------------------------------------------

def split_entries(entries: list[str], num_shards: int) -> dict[str, str]:
    """Round-robin distribute entries into num_shards shard files.

    Returns {filename: file_content} for each shard.
    """
    logging.info(f"Splitting {len(entries)} entries into {num_shards} shards...")
    bins: list[list[str]] = [[] for _ in range(num_shards)]
    for i, entry in enumerate(entries):
        bins[i % num_shards].append(entry)

    shards: dict[str, str] = {}
    for i, bucket in enumerate(bins):
        filename = f"aria2-shard-{i}.txt"
        # aria2c input format: entries separated by blank lines
        content = '\n\n'.join(bucket) + '\n'
        shards[filename] = content
        logging.info(f"  {filename}: {len(bucket)} entries")

    return shards


# ---------------------------------------------------------------------------
# Master pod — stages shard files onto the PVC
# ---------------------------------------------------------------------------

def create_master_pod_and_copy_shards(shards: dict[str, str]) -> None:
    """Spin up the master pod, mount the shared disk, and copy shards onto it."""
    logging.info(f"Creating master pod '{MASTER_POD_NAME}'...")

    shard_mount = DATA_MOUNT  # shards live under DATA_MOUNT/SHARD_SUBDIR
    master_pod = {
        "apiVersion": "v1",
        "kind": "Pod",
        "metadata": {"name": MASTER_POD_NAME},
        "spec": {
            "restartPolicy": "Never",
            "volumes": [
                {
                    "name": "pvcvol",
                    "persistentVolumeClaim": {
                        "claimName": PVC_NAME,
                        "readOnly": False,
                    },
                }
            ],
            "containers": [
                {
                    "name": "aria2c-master",
                    "image": "busybox",
                    "command": ["/bin/sh", "-c", "while true; do sleep 3600; done"],
                    "volumeMounts": [
                        {"mountPath": shard_mount, "name": "pvcvol"}
                    ],
                }
            ],
        },
    }
    subprocess.run(
        ["kubectl", "apply", "-f", "-"],
        input=json.dumps(master_pod).encode(),
        check=True,
    )
    logging.info(f"Waiting for pod '{MASTER_POD_NAME}' to be ready...")
    subprocess.run(
        ["kubectl", "wait", "--for=condition=Ready",
         f"pod/{MASTER_POD_NAME}", "--timeout=600s"],
        check=True,
    )
    logging.info(f"Pod '{MASTER_POD_NAME}' is ready.")

    # Ensure the shard subdirectory exists on the PVC
    shard_dir_in_pod = f"{DATA_MOUNT}/{SHARD_SUBDIR}"
    subprocess.run(
        ["kubectl", "exec", MASTER_POD_NAME, "--",
         "mkdir", "-p", shard_dir_in_pod],
        check=True,
    )

    logging.info("Copying shard files to the master pod...")
    for filename, content in shards.items():
        local_path = f"/tmp/{filename}"
        with open(local_path, "w") as fh:
            fh.write(content)
        remote_path = f"{MASTER_POD_NAME}:{shard_dir_in_pod}/{filename}"
        subprocess.run(
            ["kubectl", "cp", local_path, remote_path],
            check=True,
        )
        os.remove(local_path)
        logging.info(f"  Copied '{filename}' → '{remote_path}'")

    logging.info("All shard files copied.")


# ---------------------------------------------------------------------------
# Worker pods
# ---------------------------------------------------------------------------

def _list_schedulable_nodes() -> list[str]:
    """Return sorted list of all schedulable worker node names."""
    result = subprocess.run(
        [
            "kubectl", "get", "nodes",
            "--field-selector=spec.unschedulable=false",
            "-o", "jsonpath={.items[*].metadata.name}",
        ],
        capture_output=True, text=True, check=True,
    )
    return sorted(result.stdout.split())


def launch_worker_pods(num_pods: int) -> None:
    """Launch aria2c worker pods, one per shard.

    Each worker:
    - Mounts the shared PVC at DATA_MOUNT (same path as dir= in the shard files).
    - Reads its shard from DATA_MOUNT/SHARD_SUBDIR/aria2-shard-N.txt.
    - Runs aria2c with the given credentials and concurrency flags.

    Pods are hard-pinned to nodes via nodeName (round-robin across all
    schedulable nodes) so every node gets an even share of workers.
    """
    logging.info(f"Launching {num_pods} aria2c worker pods...")

    nodes = _list_schedulable_nodes()
    if not nodes:
        raise SystemExit("ERROR: no schedulable nodes found in the cluster")
    logging.info(f"  pinning across {len(nodes)} node(s): {nodes}")

    for i in range(num_pods):
        pod_name = f"aria2c-worker-{i}"
        node_name = nodes[i % len(nodes)]
        shard_path = f"{DATA_MOUNT}/{SHARD_SUBDIR}/aria2-shard-{i}.txt"

        aria2c_cmd = (
            f"aria2c "
            f"--input-file={shard_path} "
            f"--http-user={HTTP_USER} "
            f"--http-passwd={HTTP_PASSWD} "
            f"--max-concurrent-downloads={MAX_CONCURRENT_DOWNLOADS} "
            f"--max-connection-per-server={MAX_CONNECTION_PER_SERVER} "
            f"--file-allocation=none "
            f"--disk-cache=64M "
            f"--auto-save-interval=300 "
            f"--continue=true"
        )
        # Install aria2c and run download. Kernel tuning is applied by
        # Ansible on the destination nodes before pods are launched.
        command = ["sh", "-c",
                   f"apk add --no-cache aria2 && {aria2c_cmd}"]

        overrides = {
            "spec": {
                "restartPolicy": "Never",
                "hostNetwork": True,
                # nodeName bypasses the scheduler so pods are spread evenly
                # across nodes rather than piling onto a subset.
                "nodeName": node_name,
                "containers": [
                    {
                        "name": "aria2c-worker",
                        "image": "alpine:3",
                        "command": command,
                        "volumeMounts": [
                            {"mountPath": DATA_MOUNT, "name": "pvcvol"}
                        ],
                    }
                ],
                "volumes": [
                    {
                        "name": "pvcvol",
                        "persistentVolumeClaim": {
                            "claimName": PVC_NAME,
                            "readOnly": False,
                        },
                    }
                ],
            }
        }

        logging.info(f"  Launching pod '{pod_name}' on node '{node_name}' "
                     f"(shard: '{shard_path}')...")
        subprocess.run(
            [
                "kubectl", "run", pod_name,
                "--restart=Never",
                "--overrides", json.dumps(overrides),
                "--image=alpine:3",
                "--labels=app=aria2c-worker",
            ],
            check=True,
        )

    logging.info("All worker pods launched.")


# ---------------------------------------------------------------------------
# Wait / cleanup
# ---------------------------------------------------------------------------

def wait_for_pods_completion(label_selector: str = "app=aria2c-worker",
                             poll_interval: int = 15) -> float:
    """Poll until every worker pod has Succeeded or Failed.

    Returns elapsed wall-clock seconds.
    """
    logging.info("Waiting for aria2c-worker pods to complete...")
    start = time.monotonic()
    backoff = poll_interval

    while True:
        result = subprocess.run(
            ["kubectl", "get", "pods", "-l", label_selector, "-o", "json"],
            capture_output=True, text=True, check=True,
        )
        pods = json.loads(result.stdout)["items"]
        incomplete = [
            p["metadata"]["name"] for p in pods
            if p["status"]["phase"] not in ("Succeeded", "Failed")
        ]
        if not incomplete:
            logging.info("All pods have completed.")
            break
        logging.info(f"Still running: {incomplete}")
        time.sleep(backoff)
        backoff = min(backoff * 2, 60)

    elapsed = time.monotonic() - start

    # Surface any failures
    for pod in pods:
        if pod["status"]["phase"] == "Failed":
            name = pod["metadata"]["name"]
            logging.error(f"Pod '{name}' FAILED. Last 20 log lines:")
            subprocess.run(["kubectl", "logs", "--tail=20", name])

    return elapsed


def delete_worker_pods(label_selector: str = "app=aria2c-worker") -> None:
    logging.info("Deleting all aria2c-worker pods...")
    subprocess.run(
        ["kubectl", "delete", "pod", "-l", label_selector],
        check=True,
    )
    logging.info("Worker pods deleted.")


def delete_master_pod() -> None:
    logging.info(f"Deleting master pod '{MASTER_POD_NAME}'...")
    try:
        subprocess.run(
            ["kubectl", "delete", "pod", "--force", MASTER_POD_NAME],
            capture_output=True,
            check=True,
        )
        logging.info(f"Master pod '{MASTER_POD_NAME}' deleted.")
    except subprocess.CalledProcessError as e:
        stderr = (e.stderr or b"").decode(errors="replace")
        if "not found" in stderr:
            logging.info(f"Master pod '{MASTER_POD_NAME}' not found; skipping.")
        else:
            raise


# ---------------------------------------------------------------------------
# Entrypoint
# ---------------------------------------------------------------------------

def main() -> None:
    if not os.path.exists(DOWNLOADS_FILE):
        raise SystemExit(
            f"ERROR: '{DOWNLOADS_FILE}' not found. "
            "Run this script from the directory containing downloads.txt."
        )

    entries = parse_aria2c_entries(DOWNLOADS_FILE)
    if not entries:
        raise SystemExit(f"ERROR: No download entries found in '{DOWNLOADS_FILE}'.")

    shards = split_entries(entries, NUM_PODS)
    create_master_pod_and_copy_shards(shards)

    time.sleep(3)
    launch_worker_pods(NUM_PODS)

    elapsed = wait_for_pods_completion()
    delete_master_pod()
    delete_worker_pods()

    logging.info(
        f"Transfer complete: {len(entries)} files across {NUM_PODS} pods "
        f"in {elapsed:.1f}s"
    )


if __name__ == "__main__":
    main()
