- name: Install dependencies
  ansible.builtin.apt:
    name:
      - make
      - gcc
    state: latest
    update_cache: yes

- name: Copy pyxis source
  ansible.builtin.unarchive:
    src: "{{ slurm_pyxis_tarball_url }}"
    remote_src: yes
    dest: /opt/slurm/src

- name: Install pyxis
  ansible.builtin.shell:
    chdir: "/opt/slurm/src/pyxis-{{ slurm_pyxis_version }}"
    cmd: C_INCLUDE_PATH=/opt/slurm/include/ make install prefix=/opt/slurm
