FROM golang:1.25.3-alpine3.21 AS builder
RUN go install github.com/GoogleCloudPlatform/docker-credential-gcr/v2@latest

FROM registry:3
COPY --from=builder /go/bin/docker-credential-gcr /docker-credential-gcr

