- name: Create /etc/slurm directory
  ansible.builtin.file:
    path: /etc/slurm
    state: directory
    owner: "{{ slurm_user }}"
    group: "{{ slurm_group }}"
    mode: '0755'

- name: Create /var/spool/slurmctld directory
  ansible.builtin.file:
    path: /var/spool/slurmctld
    state: directory

- name: Install slurmctld.service
  ansible.builtin.file:
    src: /opt/slurm/etc/slurmctld.service
    dest: /etc/systemd/system/slurmctld.service
    owner: root
    group: root
    mode: '0644'
    state: link

- name: Create slurmctld.service.d directory
  ansible.builtin.file:
    path: /etc/systemd/system/slurmctld.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Install override.conf for slurmctld.service
  ansible.builtin.template:
    src: override.conf
    dest: /etc/systemd/system/slurmctld.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
