apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crusoe-node-remediation.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crusoe-node-remediation.labels" . | nindent 4 }}
