apiVersion: v1
kind: Secret
metadata:
  name: jupyterhub-tls
  namespace: <namespace where you deployed the helm chart>
type: kubernetes.io/tls
data:
  tls.crt: <BASE64 ENCODED CERT e.g fullchain.pem from letsencrypt>
  tls.key: <BASE64 ENCODED TLS KEY e.g privkey.pem from letsencrypt>
